lang: en-US
title: Thekaiz3n
email: thekaiz3n@pm.me
description: Personal website
author:
  name: Thekaiz3n
  twitter: ddkaiz3n
  picture: /assets/images/profile.jpeg
twitter_username: ddkaiz3n
github_username: thekaiz3n
logo: /assets/images/logo_enso.png 
search: true
search_full_content: true 

# Build settings
markdown: kramdown
#theme: jekyll-theme-basically-basic
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
plugins: # previsously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Exclude from processing.
exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - /docs # ignore Basically Basic sample site
  - /example # ignore Basically Basic dev site

# Collections


# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
